#!/bin/sh /etc/rc.common

if [ "$1" = "led" ]; then
	while [ -f /tmp/templed.lock ]; do
		if [ "$(cat /sys/class/hwmon/hwmon0/temp1_input 2>/dev/null)" -gt "75500" ]; then
			led_off $led_b
			led_on $led_r
			led_on $led_g
		else
			led_off $led_r
			led_off $led_g
			led_on $led_b
		fi
		sleep 10
	done
fi

START=97

. /lib/functions/leds.sh

led_r=bthomehubv5a:red:power
led_g=bthomehubv5a:green:power
led_b=bthomehubv5a:blue:power

start() {
	touch /tmp/templed.lock
	. $initscript led &
}

stop() {
	rm /tmp/templed.lock 2>/dev/null
	led_off $led_r
	led_off $led_g
	led_on $led_b
	sleep 10
}
